[serve]
# The address to serve on WAN.
# address = "0.0.0.0"
# The port to serve on.
port = 8000

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "tailwindcss -i styles.scss -o $TRUNK_STAGING_DIR/styles.css"]
