name: Continuous integration
on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Deps
        run: sudo apt-get update -y && sudo apt-get install libwayland-dev libgtk-3-dev libwebkit2gtk-4.1-dev libsoup2.4-dev libprotobuf-dev gcc-multilib clang libclang-dev protobuf-compiler -y
      - name: Test
        run: cargo test --all
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all -- -D warnings